# Generated by Django 4.0.1 on 2022-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('international', models.BooleanField()),
                ('eligibility', models.CharField(max_length=100)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
